version: "3.9"

networks:
  itsm_net:
    driver: bridge

volumes:
  postgres_data:
  airflow_logs:
  airflow_dags:
  airflow_plugins:
  airflow_data:

services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - itsm_net

  airflow-init:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    container_name: airflow-init
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:postgres@postgres:5432/airflow
      AIRFLOW__CORE__FERNET_KEY: "XybFUw5jh0Zz5v9M8R2phXJZ7lVdL6v3tQj1xHx0ySo="
    entrypoint: /bin/bash
    command: >
      -c "
      airflow db init &&
      airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com
      "
    networks:
      - itsm_net

  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    container_name: airflow-webserver
    restart: always
    depends_on:
      - postgres
      - airflow-init
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:postgres@postgres:5432/airflow
      AIRFLOW__CORE__FERNET_KEY: "XybFUw5jh0Zz5v9M8R2phXJZ7lVdL6v3tQj1xHx0ySo="
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./data:/opt/airflow/data
    ports:
      - "8089:8080"
    command: webserver
    networks:
      - itsm_net

  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    container_name: airflow-scheduler
    restart: always
    depends_on:
      - postgres
      - airflow-init
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:postgres@postgres:5432/airflow
      AIRFLOW__CORE__FERNET_KEY: "XybFUw5jh0Zz5v9M8R2phXJZ7lVdL6v3tQj1xHx0ySo="
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    command: scheduler
    networks:
      - itsm_net

  superset:
    image: apache/superset:latest
    container_name: superset
    restart: always
    depends_on:
      - postgres
    environment:
      SUPERSET_SECRET_KEY: "mysecretkey"
      SUPERSET_DATABASE_URI: postgresql+psycopg2://postgres:postgres@postgres:5432/airflow
    ports:
      - "8088:8088"
    command: >
      bash -c "
      superset db upgrade &&
      superset fab create-admin --username admin --password admin --firstname Superset --lastname Admin --email admin@superset.com || true &&
      superset init &&
      superset run -h 0.0.0.0 -p 8088
      "
    networks:
      - itsm_net
